apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpUser, task, between, tag
    import random
    import json

    class LoadSimulator(HttpUser):
        #wait_time = between(0.5, 1)
        json_headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
        
        @task
        @tag('tokenTest')
        def post_token(self):
            self.client.post(f"/api/tokens/test?rand=100000000")
            
        @task(10)
        @tag('tokenValidate')
        def get_token_valid(self):
            num = random.randint(1, 100000000)
            tokenId = '00000000-0000-0000-0000-' + str(num).zfill(12)
            self.client.get(f"/api/tokens/{tokenId}", name="/api/tokens/{tokenId}")