#
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-ycql-app-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  YCQL_CONTACT_POINTS: "10.204.0.57,10.204.0.52,10.204.0.97"
  YCQL_SSL_ENABLED: "true"
  YCQL_CA_PATH: "classpath:ca2.crt"
  YCQL_LOCAL_DC: "us-east1"
  YCQL_KEYSPACE_NAME: "example"
  YCQL_CONSISTENCY: "local_one"
  YCQL_SERIAL_CONSISTENCY: "serial"