#
#
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-ycql-app-config
  namespace: default
data:
  YCQL_CONTACT_POINTS: "10.204.0.130,10.204.0.111,10.204.0.122,10.204.0.131,10.204.0.121"
  YCQL_SSL_ENABLED: "true"
  YCQL_LOCAL_DC: "us-east1"
  YCQL_KEYSPACE_NAME: "example"
  YCQL_CONSISTENCY: "quorum"
