#
# TODO
# - find a way to fully externalize the application yml into a config map.
# - Improve liveness/readiness probes to be active sooner w/o failing out.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-ycql-app
spec:
  selector:
    matchLabels:
      app: sample-ycql-app
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
      labels:
        app: sample-ycql-app
    spec:
      containers:
        - name: sample-ycql-app
          image: ssherwood/yugabytedb-ycql-starter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-ycql-app-config
          env:
            - name: YCQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sample-ycql-app-db-secrets
                  key: sample-ycql-app.db.username
            - name: YCQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sample-ycql-app-db-secrets
                  key: sample-ycql-app.db.password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            limits:
              cpu: "4"
              ephemeral-storage: "1Gi"
              memory: "8Gi"
            requests:
              cpu: "4"
              ephemeral-storage: "1Gi"
              memory: "8Gi"
---
#
# Right now this autoscaler isn't all that effective since it is hard to push the CPU
# to the threshold with this application.
#
# TODO
# - find a way to use custom metrics that use the LoadBalancer that is provisioned below
#
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-ycql-app
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 65
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-ycql-app
---
#
# Deploy the load balancer service to map external client request to the "sample-ycql-app"
#
apiVersion: v1
kind: Service
metadata:
  name: sample-ycql-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sample-ycql-app